### ISSUE TITLE
Updated versions for elvui and skada

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/wow_335a_addons#6]
Elvui and skada are updated (unofficially) here :
https://github.com/ElvUI-WotLK/ElvUI/archive/refs/heads/master.zip
https://github.com/bkader/Skada-WoTLK/archive/refs/heads/main.zip

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/wow_335a_addons/commit/a0066f3342cc1d5437c6280a29b4088de47dbb38

**Comment by CraftedRO** [comment]
you can update skada too :D
